### ISSUE TITLE
Similar example output

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#102]
## Problem

When running the `btc_eth` examples the output differs quite a bit from the `erc20_btc` example. This might be confusing when using `create-comit-app` outside a workshop where this can be explained.

## Goal

When the user runs any example the output is similar so the user can relate to it. 

## Proposal

For now I would only fix the output, the behaviour of the examples CAN (should?) be different so that one can see what is possible. 

In `btc_eth`:
1. ~Log the transaction-hashes instead of the transaction return values (on logger data level) Upgrade SDK to 0.4.0.~
1. Remove it; delete it; bin it.

In `erc20_btc`:
1. Use the logger, so we can have colours as well.
2. Optional: Print more functional text (like in `btc_eth` example), move the transaction IDs to the data level.

**Comment by luckysori** [comment]
@da-kami: Updated the issue to reflect that the current `btc-eth` example should be removed instead, as discussed over the last couple of days.

**Comment by D4nte** [comment]
This is blocked by https://github.com/comit-network/create-comit-app/issues/326

@da-kami can you please move this issue under a community epic?
