### ISSUE TITLE
Example strategy

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#103]
## Goal

Improve the consistency of the examples to improve the learning speed.

## Problem

With 2 different examples we can already see that examples can be quite different in behaviour and implementation detail. At the moment there is no strategy for adding more examples.

## Proposal (list of questions and answers)

Multiple example testing against the same environment:
* If the environment changes, is it ensured that all the examples can still be run?
  * Covered by E2E tests
* Can the examples be run in any order?
  * Probably not that important for now, ensure that each example works with a fresh environment given.

Output of the example is similar
* Always use colours when logging (or never or sometimes)?
  * Always use colours
* Always have log-levels?
  * Always use log-levels (error, info, trace (technical))
* Always split between functional output and technical details?
  * Yes, like in the original `hello swap`
* Always return transaction hash?
  * Yes (the complete transaction is not useful in the console)

Behaviour proposal: 
* Maker-Taker bounce vs. all in one?
  * Change all the examples to have separate maker and taker (e.g. 2 terminals)
* Stopping after each step vs. going through?
  * Add a flag to allow that ALL examples can be manually stepped through by user.
    * Without the ability to step one cannot check anything in between (e.g. transactions, current balances...), so there is not much value to automatic steps.
    * For testing we should be able to turn the steps off.
* How to exit an example?
  * Always with 0 or 1

Example naming:
* Functional names instead of names driven by assets
  * Rename `btc-eth` to `peer-to-peer` (or `hello-swap`)
  * Rename `erc20-btc` to `using-orderbook` (or `simple-orderbook` or `auto-execute-with-orderbook`)
    * The name does not have to be overly complicated, each example has a README where we can specify details of what the example is about.

**Comment by D4nte** [comment]
My 2 cents

>     * Multiple example testing against the same environment
What do you mean ? Yes, given a certain environment, a user should be able to run all examples sequentially.
 
>     * Output of the example is similar     
>       * Always use colours when logging (or never or sometimes)?
Yes
>       * Always have log-levels?
Yes, 3 levels: error, info, trace(technical)
>       * Always split between functional output and technical details?
See above
>     * Different behaviour in examples
>       * Maker-Taker bounce vs. all in one (should all the examples have the same behaviour...?)
Only have the separate maker/taker bounce (ie, 2 terminals)
>       * Stopping after each step vs. going through
Running through as we initially had.
>     * Example naming
? 
> Behaviour proposal:
>     * I'd propose to have examples where we have both parties in one (as currently) and examples where we have maker and taker separate.
👎
>     * Change ALL examples to be manually stepped through by user.
👎

>     * Functional names instead of names driven by assets
>       
>       * Rename `btc-eth` (aka `hello-swap`) to `simple-dex`
>       * Rename `erc20-btc` to `simple-swap-erc20-btc` (?)

If you wish to have different hello-swap that describe different apps then my counter proposal: have a more descriptive folder structure?

```
examples
 |- simple-dex
     |- eth-btc
     |- erc20-btc
 |- some-app
     |- eth-btc
```

However, I would argue that the example should not be a simple dex but the simplest run (hello world) and hence that all examples are the same just with different asset pairs.

**Comment by da-kami** [comment]
> If you wish to have different hello-swap that describe different apps then my counter proposal: have a more descriptive folder structure?

There is no `hello-swap` as such any more, at least that was the conclusion after our discussion on how to go on with create-comit-app and hello-swap. 

The idea is to have many examples and we recommend one to start with (we can name that hello-swap if we want...).

Having a more descriptive folder structure definitely helps. I proposed to be more _functional_ driven when it comes to the name. `btc-eth` is not a good name from my point of view. It only explains what is swaps, but not what the example represents. Hence my suggestion. We can go for the folder structure you propose, but for most examples it should be flat (changing the assets should _configuration_ and NOT be the main point of an example from my point of view).

**Comment by da-kami** [comment]
Closed because I don't know what to do with it. Will open separate issues to align the examples.
