### ISSUE TITLE
Windows release 

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#105]
## Problem

For the Hackathon in Dez. we might have Windows users. Windows is currently not supported.

## Goal

Release create-comit-app for native Windows.

## Proposal

Time-box this. Since create-comit-app is reasonably small we don't have to use github-actions.

**Comment by da-kami** [comment]
recommendation: must (timeboxed)

**Comment by thomaseizinger** [comment]
Note: I think we _should_ definitely use github actions! (we just don't need to wait for them having proper caching)

**Comment by D4nte** [comment]
1. Block it on the Mac OS issue, once the mac os one is done, it should be easy to copy-paste for windows in GitHub Actions
2. Windows includes 2 environments:
  - Native Windows
  - Linux subsystem

I believe we should scope this and decide what we aim for.

**Comment by D4nte** [comment]
Please note code changes are required to support signal handling on Windows: https://github.com/comit-network/create-comit-app/runs/269394691

**Comment by da-kami** [comment]
Being a Hackathon requirement - shouldn't this be a must?

**Comment by bonomat** [comment]
yap, moved it.
