### ISSUE TITLE
Funding problem

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#106]
## Problem

Currently the environment is static, there is no configuration possible to add funds to a certain account/address. 

## Goal

Be able to fund somehow.

## Proposal

Add commands in create-comit-app to allow funding of a running environment. (configuration files are an alternative, but make things even more complicated).

In the long run we should work on the infrastructure in general (like providing faucet, testnet setup and similar for workshops - this needs more thought though), see

**Comment by da-kami** [comment]
recommendation: could

**Comment by D4nte** [comment]
It is not clear to me whether you are talking about regtest or testnet as you mentioned testnet.

Also, until we have an actual requirements, I do not see the point in adding the flexibility

**Comment by luckysori** [comment]
Closed because no need to future-proof.
