### ISSUE TITLE
Intercommunication between participants of a workshop

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#107]
## Problem

When we do a workshop people cannot communicate with each other at the moment. Everything is just on the local machine.

When we did our first workshop in Singapore using comit-i we had a lot of dynamic resulting from the fact that people could interact with each other on the UI. The current workshops don't allow that.

## Goal

Be able to have interaction between participants for workshops.

## Proposal

Grab a mate and a room and come up with an interactive example first. Then decide on the technical requirements. 

Network ideas:

* Add a `--network` flag to create-comit-app's `start-env` command. 
* Setup regtest network somehow. 
* Provide another docker image that enables communication through regtest network that we set up.

**Comment by D4nte** [comment]
Creating a bitcoin regtest network is easy.

However, what do you expect them to do ? Each run one side of an example app?

What I would like to see is more a proposal of a new "multi-participant" example.
Once this proposal is done, we can work on the technical requirements.

I would like to generally avoid the fine-grain to big-pictures tickets but instead talk about the big picture first and then deduce the changes necessary.

**Comment by da-kami** [comment]
meeting planned for 29.10. 10:30 together with @D4nte :)

**Comment by da-kami** [comment]
Conclusion: 
- create-comit-app is made for local development
- we are not adding P2P regtest  (i.e. swap between different hosts) to the examples
- we don't add testnet to create-comit app

Moving towards an interactive example by using testnet: 
- first iteration: document manual steps needed to swap on testnet, see: https://github.com/comit-network/comit-rs/issues/1592
- second (or n-th) iteration: make using testnet a piece of 🍰 on the cnd side, see: https://github.com/comit-network/comit-rs/issues/1503
