### ISSUE TITLE
ERC20-BTC example cannot be automatically tested

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#109]
## Problem

The ERC20-BTC example cannot be _easily_ tested as part of the CI as it requires shell interaction.

## Goal

Automate run of all examples to ensure our user can always run them

## Recommendation

`yes |` command during tests, @D4nte.

## Priority Justification

As it is not tested, we could end up with a non-working example in the repository which could impact COMIT App devs or comit workshops.

**Comment by bonomat** [comment]
Can you describe this issue a bit more please? Imho _"Cannot be automatically tested"_ is not clear enough. 
Meaning, Describe the issue and the pain points please.
