### ISSUE TITLE
Propose alternative to use starting environment twice

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#115]
## Problem

Currently, if the user run `start-env` (or `yarn run env`) twice, it just exit providing with a way to force a start (ie, delete the lock file).

This means if there an issue, the user needs to go and manually delete a file and possible kill some docker containers and remove a docker network! (which is not even explained).

## Goal

Allow the user to clean up the environment without any pre-requisite knowledge

## Recommendation

When `start-env` is ran, if the `~/.create-comit-app` folder is already here, ask the user: `An environment is already running, do you want to stop it and start a fresh one?`:
- `N/No/CTRL-C`: Do nothing and stop.
- `Y/Yes`: Do a clean-up and start a new environment.

Clean-up:
1. Kill other create-comit-app instance (to do so, create-comit-app needs to save its own pid in `~/.create-comit-app/run.pid`
2. Wait till it's dead
3. Remove docker containers (if any remaining)
4. Remove docker network (can only be done once docker containers are removed)
5. Delete `~/.create-comit-app` folder

**Comment by bonomat** [comment]
This sounds like a perfect candidate for: let's ask the user. We had some devs trying it out already, shall we reach out to them and ask how they would like to use the tool?

**Comment by D4nte** [comment]
> This sounds like a perfect candidate for: let's ask the user. We had some devs trying it out already, shall we reach out to them and ask how they would like to use the tool?

I am pretty confident on this one, there are other things that we dropped when discussing with @thomaseizinger as we wanted to have user feedback first. However, happy to survey some of our workshoppers first if you prefer.

Please note the strategy here is to replicate the behaviour of a successful tool: React-scripts.

**Comment by bonomat** [comment]
I think this is a minor optimization which we do not need for now.
