### ISSUE TITLE
Peer-to-peer Workshops

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#123]
Results of discussion between @da-kami & @D4nte on 29Oct2019.

## Objectives
- Allow better understanding of COMIT by running examples with 2 parties (separate hosts)
- Get workshop participant excited thanks to the following properties:
  - It works in a peer-to-peer context (participants swap with each others)
  - They are inspired as they were demonstrated various use-cases

## Constraints
- Time: Workshops are time-limited
- Skills: Participants may have a various level of skills
- Network: Assumed participants are on common wifi network. Reliable Internet access is questionable
- Step-by-step: The example still need to be run step-by-step for demonstration purposes

## Examples

After debate taking in account the **Objectives** and **Constraints**, we propose to create 3 new examples.

### 1. Simple LAN

A simple example that runs a Maker/Taker over the LAN.

#### Technical solutions

- Use regtest due to time constraints (blocks every 20min on Bitcoin testnet3).
- Modify create-comit-app to allow the creation of a regtest network

##### Regtest network - Reproducible

Modify create-comit-app to allow the creation of a full network, meaning that most likely:
- new command `start-master-env` that starts a bitcoind and parity nodes. Bitcoind nodes generates blocks. Parity node is the only one
- new options on `start-env` that allow the passing of the IP address of the master host. A bitcoind is started to connect to the master bitcoind. The connection details IP for the master parity node are dumped in the env file to allow examples to connect directly to master parity. This bitcoind does not generate.

Pros:
 - Any workshopper, dev, group that wishes to run such example can without relying on us

Cons:
 - Bit more work?
 - Detailed explanations needed on how to do the setup (yet, should be facilitated by create-comit-app)

##### Regtest network - Remote nodes

The second solution is to host remote regtest parity/bitcoind nodes on a fixed location (regtest.coblox.tech).

Modify create-comit-app to allow the connection to such remote node. Similarly to the **Reproducible** solution without the `start-master-env` part:
- new options on `start-env` that allow the passing of the IP address of the remote host. A bitcoind is started to connect to the remote bitcoind. The connection details IP for the remote parity node are dumped in the env file to allow examples to connect directly to master parity.

Note: The proposal is based on using what we know works (single Parity Instant Seal node), it would technically be better yet more difficult to have multiple Parity PoA setup).

### 2. Invitation/Negotiation protocols

The aim is to demonstrate the usage and potential of the invitation and negotiation protocols.

This  example is expected to be built on example 1 with added code.

Separate discussion to happen to fix the scope.

### 3. GUI

The aim is to excite the workshop participants by demonstrating how a simple GUI would look like.

This is still an example and hence should be of minimal size (challenge to make it under 500lc :D).

This GUI could be for the taker only and could be run against whatever other maker example.

**Comment by da-kami** [comment]
Move to not now, because we will focus on testnet for the Hackathon. 
Setting up regtest for P2P trading is a nice to have for workshops but the effort is not worth the gain at the moment.

**Comment by bonomat** [comment]
@D4nte / @da-kami : I don't see this as an immediate priority. Let's put this back into focus once we plan our next workshop?
If you agree, please go-ahead and close this epic.

**Comment by D4nte** [comment]
I'll let @da-kami decide.

**Comment by bonomat** [comment]
kinda outdated, let's close this as there is no workshop planned in the near future.
