### ISSUE TITLE
Make it easier for users to run the application

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#13]
**Goal:** Make it easier for users to run the application

**Problem:** The binary name is very long.

**Recommendation:** Rename the binary name to `cca` so that people only have to type `cca start-env`.

**Comment by D4nte** [comment]
`cr<tab>` :)

**Comment by thomaseizinger** [comment]
@thomaseizinger to nudge people and get a response from everyone

**Comment by thomaseizinger** [comment]
Let's leave it for now and wait if someone complains.
