### ISSUE TITLE
`hello swap` does not represent the current SDK

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#135]
## Problem

The examples in create-comit-app differ in behaviour and dependencies on different SDK versions.

## Goal

Align the example behaviour to represent what we want to show to the user. 
Examples should always work against the latest SDK version.

## Proposal 

~After a lengthy discussion with @bonomat, @D4nte and @luckysori we agreed that we want to stick to the current SDK version and not show other examples.~
~Remove `btc-eth` (aka `hello swap`) example.~

After re-discussion we came to the conclusion that the example is still nice as a more low-level example, and we shall keep it for the hackathon to see if people have a look.

The example HAS to work against the newest SDK version though, thus: Update so it works against the current SDK version.

**Comment by bonomat** [comment]
When this is done, please rename the newly added example from the PR #129 to `btc-eth`
