### ISSUE TITLE
Inform users what is going on when using the application

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#15]
Currently, the application doesn't print any output until the blockchain nodes have started up.

**Problem:** The user has no feedback for about 5 seconds on whether or not anything has happened.

**Goal:** It should be clear to the user, what the application is doing.

**Recommendation:**

Light-weight solution: Log something _before_ and _after_ an asynchronous task, like:

```
> Starting bitcoin node ...
> Done.
> Starting ethereum node ...
> Done.
etc ...
```

Long-term solution: Provide interactive output of what is happening, with animations etc.

**Comment by D4nte** [comment]
Already in progress..

**Comment by bonomat** [comment]
> Already in progress..
@D4nte if it is, can you assign it to you and set it to progress please?
