### ISSUE TITLE
Extended `create-comit-app` documentation

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#169]
## Problem

Without running a workshop it is a bit difficult to find your way into `create-comit-app`.
It is great how the examples evolved so far, but there is room for improvement.

## Goal

Improve the ease of understanding create-comit-app. 

## Proposal

* Pick one example that shall be the "getting started" example. -> Separate Taker/Maker
* Add comments to the "getting started" example that explain the steps in detail. 
   * The goal is to explain the sections clearly. A person should be able to understand the example without asking a COMIT team member for help.
* Extend the README to explain the "getting started" example (and other examples)

**Comment by D4nte** [comment]
The feedback we have received at a recent call would suggest that we also **state what to do next once you have run an example**.

My suggestion would be to implement #181 and then direct the developer to these snippet + the full swap demo code to write its own app.,

**Comment by da-kami** [comment]
done https://github.com/comit-network/create-comit-app/pull/234

**Comment by D4nte** [comment]
Re-opening as to me, the "what's next" point does not seem resolved.

**Comment by bonomat** [comment]
These are all valid concerns, however, closing this as `Without running a workshop` - approach to create-comit-app is only focus of Q2.
