### ISSUE TITLE
`separate-app` taker does not exit on outdated order

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#173]
## Problem

When a taker sends an outdated order to the maker the maker auto-declines and end, but the taker does not react to the decline and goes on.

Maker output:
```
yarn run maker
yarn run v1.19.1
warning ../../package.json: No license field
$ DOTENV_CONFIG_PATH=$HOME/.create-comit-app/env ts-node -r dotenv/config ./src/maker.ts
[Maker] Bitcoin balance: 8. Ether balance: 100
[Maker] peer id: QmaEqwyVYbc9uNDsyocXtejXTeM4S9pN4Fn18HPDySSoez
[Maker] address hint: /ip4/127.0.0.1/tcp/9939
Waiting for someone taking my order at: http://localhost:2318/orders/ETH-BTC
Negotiation Protocol listening on port 2318!
Requested order is invalid
✨  Done in 324.37s.
```

Taker output:
```
yarn run taker
yarn run v1.19.1
warning ../../package.json: No license field
$ DOTENV_CONFIG_PATH=$HOME/.create-comit-app/env ts-node -r dotenv/config ./src/taker.ts
[Taker] Bitcoin balance: 12. Ether balance: 100
0. Ready?
[warning] (net) Peer disconnected with requested blocks.
[warning] (net) Resending sync...
Received latest order details: ether:bitcoin for a rate of 9:1
Swap started! Swapping 9 ether for 1 bitcoin
1. Continue?
```

Eventually the taker gets a timeout, but it still "hangs" forever and does not exit:

## Goal

In such a scenario the taker should properly exit on decline.

## Proposal

Let the taker react to the decline and exit with "order outdated".

**Comment by D4nte** [comment]
I would be against adding advance logic to examples, making them harder to understand.

**Comment by D4nte** [comment]
My proposal: Create a new _code_ example that shows how to handle if the maker decline the swap and hence `fund()` time out.

**Comment by da-kami** [comment]
My conclusion:

1. If I need a `demo` folder that goes to far - if it is needed it should not be inside `create-comit-app`
2. The examples need a roadmap. 

Details:

@D4nte what you state is totally valid, but I think we have to see the bigger picture - this goes back to having a clearer roadmap for the examples.

I think we are mixing up different problems:

1. Demo vs. Example
2. Happy path example vs. other example
3. Example complexity & SDK

My thoughts:

As much as I would like that for my demos, I don't think we should have a `demo` folder in create-comit-app, it would be confusing for people (like: what is the difference between `example` and `demo`?). 

I do think we should have examples that show `refund` as well. 
In general we should come up with what I called `example strategy` in the past:

1. What examples do we want?
2. How complex is an example allowed to be?
3. What features do all the examples share?
4. What should live in the example and what should be provided by the SDK?
