### ISSUE TITLE
Set CORS config for CND

### ISSUE THREAD

**Issue by bonomat** [comit-network/create-comit-app#188]
## Problem:

With comit-network/comit-rs#1553 (and comit-network/comit-rs#1650) a new config field was introduced to set allowed CORS origins.

## Goal: 

Allow create-config-app to set the CORS field.

## Recommendation: 

Default to allow all origins.

**Comment by bonomat** [comment]
## Problem:

With comit-network/comit-rs#1553 (and comit-network/comit-rs#1650) a new config field was introduced to set allowed CORS origins.

## Goal: 

Allow create-config-app to set the CORS field.

## Recommendation: 

Default to allow all origins.

**Comment by thomaseizinger** [comment]
In order to do this, we will need a new release of cnd first!

**Comment by D4nte** [comment]
> ## Problem:
> 
> With [comit-network/comit-rs#1553](https://github.com/comit-network/comit-rs/issues/1553) (and [comit-network/comit-rs#1650](https://github.com/comit-network/comit-rs/pull/1650)) a new config field was introduced to set allowed CORS origins.
> ## Goal:
> 
> Allow create-config-app to set the CORS field.
> ## Recommendation:
> 
> Default to allow all origins.

Note this is a comment and not the description.

**Comment by da-kami** [comment]
done https://github.com/comit-network/create-comit-app/pull/222/files
