### ISSUE TITLE
Making it clear that certain code-parts of examples are for `demo` purpose

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#206]
## Problem

Stopping the example (i.e. stepping through the example) is for demo purposes. If we want to motivate people to create applications this is confusing. 

## Goal

Separate the demo and the code-examples. 
Code-examples should be executable but have the purpose to be self-explanatory and focus on the code.
Demo-examples must be executable and have the purpose to showing stuff live.

### Short run (for hackathon and workshops in Europe):

Add a `--demo` flag to the `separate-apps` and the `erc20-btc` examples. 
Default: no steps
If `--demo` is given execute the steps (wrap all stepping with ifs)

(Because we showcase both of them in hackathon and the workshops in Europe)

### Long run (January)
https://github.com/comit-network/create-comit-app/issues/181

**Comment by D4nte** [comment]
I believe this was done in the short run to the hackathon.

For the long run, I'd prefer https://github.com/comit-network/create-comit-app/issues/326 to be tackled instead.

I'd like to mark this as superseded by https://github.com/comit-network/create-comit-app/issues/326.
Let me know what you think.

**Comment by da-kami** [comment]
already done.
