### ISSUE TITLE
Separate-apps gets stuck when funding Ethereum

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#245]
## Problem

Somehow the funding transaction is not properly executed. This might be related to the swap not being accepted automatically in the SDK.

The bigger problem is, that there is that there is no error handling, the fund step just times out and it is unclear what is happening. The swap remains unfinished indefinitely which may result in weird environment behaviour.  

The problem occurs quite often, I had it in 2 out of 6 swaps.

![image.png](https://images.zenhubusercontent.com/5ccfab6d577faf2d7f9f9b99/6bc60a16-08eb-47ba-8dda-2d2a92cf8739)

**Comment by da-kami** [comment]
linked to an old version of the SDK, it seems to be fixed. if happens again re-open.

**Comment by D4nte** [comment]
I fixed it with #233
