### ISSUE TITLE
`yarn run example`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#267]
## Problem

Currently, each example is a separate npm package. This has several problems:

- Duplication in the package.json file in terms of scripts & dependencies
- We have to run `yarn` for each example in order to install it

## Goal

A more light-weight example folder.

## Recommendation

- Remove the `package.json` from each example
- Introduce a sub-command in the `new_project` package `example` that allows users to run an individual example like so: `yarn run example btc_eth`

For the separate apps example, it could be: `yarn run example separate_apps -- taker`

**Comment by D4nte** [comment]
I think we should do #181 first to see how we want to evolves the examples for purpose of helping a dev build a COMIT App, hence marking the dep for now.
