### ISSUE TITLE
Simplify build script/process

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#268]
## Problem

Currently, we have 2 feature flags and several conditional code paths to support windows or unix, depending on which platform we want to build for. This is because cargo [does not support compiling a dependency with different features based on the target platform.](https://github.com/rust-lang/cargo/issues/2524).

## Goal

No feature-flags in our build process for support multiple platforms. `cargo build` should work on each platform (Linux, Windows, MacOS) and produce a binary that works.

## Recommendation

I believe we might be able to fix some thing things downstream in the `shiplift` crate that would allow us to "just" depend on shiplfit and shiplift it self compiles according to the target platform without and special feature flags.

**Comment by bonomat** [comment]
Hi @thomaseizinger, can you refine this ticket's scope please? Currently it is not clear when this ticket is done.
