### ISSUE TITLE
Create-comit-app can be started twice

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#28]
**Problem:** Create-comit-app can be started twice.

a) This takes up unnecessary resources
b) It can be confusing to the user
c) It might actually cause problems because we use static names for docker containers and networks

**Recommendation:** Fail if we find a `.env` file in the current directory.

**Comment by D4nte** [comment]
See #32 for a proposal

**Comment by D4nte** [comment]
Superseded by #32
