### ISSUE TITLE
Support ERC20 in `separate-apps` like example

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#290]
## Problem

There seems to be issues when integrating ERC20 `separate_apps` style, i.e., with the latest SDK API that we would expect a dev to use.

## Goal

To allow ERC20 integration as the aim is to provide LN<>ERC20 App, create a `separate_apps` example that swaps to ERC20 instead of Ether.

## Recommendation

Go for it, hit the bugs fix them in the SDK and fine some help when needed.

----
_Old issue for reference_
## Problem

As a user I would assume that I can change the Ether to ERC20 easily in order to swap the tokens setup in the contract (combine the erc20-btc and the separate-apps examples). 
However, this is not easily possible.
It seems like the ERC20 token is supported in the negotiation (there is code to handle the tokens...), but the token contract we generate is not registered in the `definitions`. I find that quite confusing. Took me some time to figure out what the problem was - and once I fixed it (registered the token there correctly), the example just gets stuck (most likely because of the additional deployment+fund step? - I did not investigate further)...

## Goal

Better user experience, it should be possible to combine the examples when learning. 

## Proposal

Since we have to discuss how we move forward with the examples and the SDK in general I will not write a lengthy solution here, but just report: At the moment it is not enough. If it is confusing for me, what about somebody that is not familiar with the codenbase 😅

**Comment by bonomat** [comment]
I see two problems here:
1) SDK only accepts pre-defined token contracts.
2) There is a lack of instruction for doing an atomic swap between ERC20/BTC (you assume that you forgot to call `deploy` before `fund`)

Is this correct? If so, can you create two tickets please?

**Comment by thomaseizinger** [comment]
> There is a lack of instruction for doing an atomic swap between ERC20-*(you assume that you forgot to call deploy before fund)

The issue here is actually deeper and we should reflect on the SDK design:

cnd actually tells you at runtime what you should do next. Our SDK shouldn't blatantly assume that it is smarter and ignore that.

**Comment by D4nte** [comment]
> > There is a lack of instruction for doing an atomic swap between ERC20-*(you assume that you forgot to call deploy before fund)
> 
> The issue here is actually deeper and we should reflect on the SDK design:
> 
> cnd actually tells you at runtime what you should do next. Our SDK shouldn't blatantly assume that it is smarter and ignore that.

Didn't you already discuss that when I highlighted it was confusing that a dev has to know to deploy before funding in ERC20.

**Comment by da-kami** [comment]
@D4nte could you please refine this? I am not sure how we want to tackle the problem to be in line with our Q1 goals. Probably easier if you refine it if that's OL :)

**Comment by D4nte** [comment]
Good point, I think we need it for Yos to progress.

**Comment by bonomat** [comment]
This ticket is still too generic and does not describe _one particular_ problem. 
I would not know what needs to be done nor how to estimate it. 

Checkout my first comment: 
>I see two problems here:
> 1) SDK only accepts pre-defined token contracts.
> 2) There is a lack of instruction for doing an atomic swap between ERC20-*(you > assume that you forgot to call `deploy` before `fund`)

Imho the problem you describe here is addressing 1). If so, shall we change that description to reflect that?

**Comment by D4nte** [comment]
> This ticket is still too generic and does not describe _one particular_ problem.
> I would not know what needs to be done nor how to estimate it.
> 
> Checkout my first comment:
> 
> > I see two problems here:
> > 
> > 1. SDK only accepts pre-defined token contracts.
> > 2. There is a lack of instruction for doing an atomic swap between ERC20-*(you > assume that you forgot to call `deploy` before `fund`)
> 
> Imho the problem you describe here is addressing 1). If so, shall we change that description to reflect that?

Please see this issue as a _user story_, the aim is to have an example like `separate_apps` but for erc20.

If this is deemed too big then it can be split up but the team at grooming time.

**Comment by da-kami** [comment]
@D4nte was this ticket actually tackled?

**Comment by D4nte** [comment]
> @D4nte was this ticket actually tackled?

It is not. I am not sure it is worth the effort at this time.

**Comment by da-kami** [comment]
Out of scope at the moment. 
Re-open later if deemed necessary.
