### ISSUE TITLE
git somehow expects the `user.name` to be set when checking out `Hello-Swap`

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#31]
during the workshop we had one participant running into this issue:

```
./create-comit-app new my-cool-app
thread 'main' panicked at 'Failed to create initial commit: Error { code: -3, klass: 7, message: "config value \'user.name\' was not found" }', src/new.rs:25:22
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
```

seems to be related to the git configuration

**Strong recommendation**: Do `git init` but do not do an initial commit.

**Comment by D4nte** [comment]
I don't think we should do git init

**Comment by thomaseizinger** [comment]
Can do git init without doing an initial commit I think :)
