### ISSUE TITLE
Yarn command fails with invalid argument

### ISSUE THREAD

**Issue by yosriady** [comit-network/create-comit-app#312]
I may have encountered a regression with the `create-comit-app` CLI.
I was able to successfully run this during the hackathon, but running `yarn create comit-app` appears to fail now:

```
~ yarn create comit-app my-comit-app
yarn create v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-comit-app@0.6.0" with binaries:
      - create-comit-app
[#################################] 33/33error: Found argument 'my-comit-app' which wasn't expected, or isn't valid in this context

USAGE:
    create-comit-app <SUBCOMMAND>

For more information try --help
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-comit-app
Arguments: my-comit-app
Directory: /Users/yos
Output:
```

**Comment by D4nte** [comment]
Hi Yos,

Being able to do `yarn create comit-app my-comit-app` is not yet released.
For now you still need to do `yarn create comit-app new my-comit-app`.

I'll trigger a release now so that you can do it without the `new` argument.

**Comment by yosriady** [comment]
Got it. I was following step 1 of the documentation. 
I'll keep an eye out for other stale instructions.

<img width="849" alt="Screenshot 2020-01-06 at 12 04 46 PM" src="https://user-images.githubusercontent.com/1084226/71794513-d2dd0700-307c-11ea-945c-afb334c1660e.png">

**Comment by D4nte** [comment]
> Got it. I was following step 1 of the documentation.
> I'll keep an eye out for other stale instructions.
> 
> <img alt="Screenshot 2020-01-06 at 12 04 46 PM" width="849" src="https://user-images.githubusercontent.com/1084226/71794513-d2dd0700-307c-11ea-945c-afb334c1660e.png">

Hi Yos, yes it is because the documentation is from `master`.
But you are absolutely right we should have released as soon as it got merged as it is a major UX change.
I am currently in the process, hopefully will be done by tomorrow.

**Comment by D4nte** [comment]
This is now fixed with the latest release: https://github.com/comit-network/create-comit-app/releases/tag/0.7.0
