### ISSUE TITLE
Improve ergonomics & feedback 

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#32]
## Problems

1. User must run `new` then `cd` the new folder and then run `start-env`. Failure to do so will return unclear errors.
2. If a user tries to run `start-env` twice, he gets unclear errors.
3. The folders used to mount docker volumes, currently stored at `/tmp/create-comit-app` are not cleaned-up.

## Goal

1. Remove the `cd` step.
2. Explicitly stop the user to run `start-env` twice on the same machine.
3. Clean-up the folders used for volume
4. Update hello-swap if needed (open new issue)

## Recommendation

As per the [Linux Information Project](http://www.linfo.org/var.html):

> Among the various subdirectories within /var are /var/cache (contains cached data from application programs), /var/games (contains variable data relating to games in /usr), /var/lib (contains dynamic data libraries and files), /var/lock (contains lock files created by programs to indicate that they are using a particular file or device), /var/log (contains log files), /var/run (contains PIDs and other system information that is valid until the system is booted again) and /var/spool (contains mail, news and printer queues).

1. Hence, the proposal would be to replace `./.env` with `/var/run/create-comit-app/env`.

2. This could then be used as a `lock` file, meaning, if the file exists and a user runs `start-env` then an error should explain that it seems like an instance is already running:

```
▶ create-comit-app start-env > /dev/null 2>&1 &
[1] 71840
▶ create-comit-app start-env
An environment is already running!
If you are sure that no other `create-comit-app start-env` process is running, delete the lock file at `/var/run/create-comit-app/env`.
```

3. Finally,  move the temp folders under the same `/var/run/create-comit-app/` so start-env can delete the whole folder at the end (instead of just the env file).

**Comment by thomaseizinger** [comment]
Maybe we should also daemonize `create-comit-app` after `start-env` so the user can use their terminal again?
