### ISSUE TITLE
Separate examples per concerns

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#326]
## Problem

The current examples are fulfilling 2 concerns:
1. Show how to code a COMIT App (e.g. code comments in `separate_apps`)
2. Demonstrate and explained how an atomic swap is run (e.g. use of `readLineSync` to make the run interactive)

Several times we have evolved examples for 2. to the detriment of 1.

Moreover, with the new accountability structure, 1. Falls under product (devex) and 2. under community.

## Goal

Remove any possible conflict/friction/obstacle for the various streams to be done.

## Recommendation

1. Create a new `demo` folder beside the existing `example` folder
1. Duplicate the `separate_apps` (and improve naming) to the `demo` folder, strip the code from the comments.
1. In `examples/separate_apps`, remove the interactiveness
1. Decide if something similar needs to be done for `btc_eth` and `erc20_btc`.

## Priority Justification

This is a pre-requisite to any future evolution of the examples (e.g. from workshop feedback).
> In `examples/separate_apps`, remove the interactiveness

Should be done with the "get ready" documentation so this example becomes the target COMIT App that we build in the get ready doc.

**Comment by da-kami** [comment]
@D4nte isnt's this already done and merged?

**Comment by D4nte** [comment]
Done with #383
