### ISSUE TITLE
Publish create-comit-app on npm

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#35]
## Problem

User has to:
1. Find the create-comit-app repo
2. Select the right binary for its platform
3. Download the binary
4. unzip the binary
5. execute the binary

## Goal

Reduce the steps above by publishing create-comit-app on npmjs.com as it is the one guaranteed package manager that a TS/JS dev uses.

I check https://www.npmjs.com/policies/open-source-terms#acceptable-use and https://www.npmjs.com/package/create-react-app and it should be fine.

## Recommendation

Upload various binaries on npm (one for each platform) so that a user can just do:

```
npx create-comit-app
# or 
yarn add create-comit-app && create-comit-app
```

**Comment by thomaseizinger** [comment]
I am not sure I see the usefulness in this.
Either we make an npm package that downloads and wraps create-comit-app or we compile it to webassembly and ship it as a native JS thingy.

The first one doesn't add any value. People should be able to download a binary from GitHub.

The second one seems unrealistic given we have, on purpose, quite some IO activity in cca.

So what is the gain of this? Hint: following the problem-goal-solution template might be useful for tickets like these :)

**Comment by D4nte** [comment]
It does not work...
