### ISSUE TITLE
Link to maker is confusing

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#371]
Similar to https://github.com/comit-network/comit-js-sdk/issues/88

## Problem

https://github.com/comit-network/create-comit-app/blob/master/create/new_project/examples/separate_apps/src/maker.ts#L87

This _invitation link_ 
- exposes internal wire of the sdk (use of http for negotiation communications)
- is hard coded

Because of that, instead of being inspiring, it just creates more confusion.

## Goal

- Do not expose unnecessary details to developer
- Provide appropriate function to the developer via the SDK
- Update sdk, release and update example

## Recommendation

I see several choices:
1. ~Just remove it from example.~
1. Modify the SDK to provide a function that returns this value and be clearer on what it would be used for: `makerNegotiator.getUrl() // Returns the an url that can be used by a taker to trade with us.` (would need to move this issue to sdk repo)

_Edit: After writing #comit-js-sdk#90 I'd be more keen to go for 2._

**Comment by D4nte** [comment]
@yosriady please review and confirm that I captured your feedback correctly.

**Comment by yosriady** [comment]
@D4nte 

```
const invitationDetails = `http://localhost:2318/orders/ETH-BTC`;
```

Yes, exposing an HTTP interface leaks too many details. SDK functions can replace these, for example:

```
sdk.getInvite()
```

Another example:

```
https://github.com/comit-network/create-comit-app/blob/master/create/new_project/examples/separate_apps/src/maker.ts#L61-L64

    // Start the HTTP service used to publish orders.
    const makerHttpApi = new MakerHttpApi(makerNegotiator);
    // The maker's HTTP service will be served at port 2318.
    makerHttpApi.listen(2318);
```

Users shouldn't think about any internal HTTP APIs, so maybe this could be abstracted away: 

```
maker.start()
```

**Comment by D4nte** [comment]
> Users shouldn't think about any internal HTTP APIs, so maybe this could be abstracted away:
> 
> ```
> maker.start()
> ```

Covered/Updated in https://github.com/comit-network/comit-js-sdk/issues/88
