### ISSUE TITLE
Cleanup environment command is annoying

### ISSUE THREAD

**Issue by bonomat** [comit-network/create-comit-app#388]
# Problem

More then once I just wanted to run an example and had a _broken_ environment. 
create-comit-app nicely response with: 

```
It seems that `create-comit-app start-env` is already running.
If it is not the case, run `create-comit-app force-clean-env` and try again.
```

It is annoying to have to run two commands to be able to run an example.

# Goal

Smoother developer experience

# Recommendation

Instead of having an extra command for cleaning up the environment I would like to see it as a parameter to start-env, e.g.
```
create-comit-app start-env --force-clean-env
```

**Comment by thomaseizinger** [comment]
`create-react-app` has a similar problem with the port it is told to bind to already being taken.

Instead of failing, they ask the user: "Do you want me to bind to port XYZ instead?"

We could ask: "I've found a running environment. Do you want me to kill that one and start a new one?"

**Comment by D4nte** [comment]
Either way sounds fine to me.

**Comment by bonomat** [comment]
@thomaseizinger : Not sure if I understand your proposal correctly. Does the user still have to say `yes please` :D ?
 
Imho it should be possible to start a clean environment with one command completely interaction free.

**Comment by thomaseizinger** [comment]
> @thomaseizinger : Not sure if I understand your proposal correctly. Does the user still have to say yes please :D ?

By default yes, but a common comandline thing to do is to have a `--yes` flag that says yes to everything :)

**Comment by D4nte** [comment]
Sounds good to ahve best of both world by introducing a wizard and a non-interactive command line argument.

**Comment by D4nte** [comment]
Wasting time discuss this ticket, drop it until a user asks for it.
