### ISSUE TITLE
Redesign using async/.await

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#40]
## Problem

CCA has a quite some complexity because it is basically a composition of a lot asynchronous tasks (Futures).

## Goal

An easy to maintain and understand codebase.

## Recommendation

Move the whole codebase to async/await and `async-std`.
As part of this re-design, consider problems like:

- https://github.com/comit-network/create-comit-app/issues/41

**Comment by D4nte** [comment]
refine?
