### ISSUE TITLE
Image trait is doing too much

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#41]
## Problem 

`Image` trait is implemented for both blockchain nodes and cnd, but it has a method `new` which instantiates clients for the blockchain nodes yet does nothing for `cnd`:

https://github.com/comit-network/create-comit-app/blob/57fe0c7e55d07dad3ea2215f9fbacbad217ad4bf/src/docker/cnd.rs#L28-L30

This is dead, useless code.

## Goal

To not have dead, useless code.

## Recommendation

Move `new` function from `Image` to `BlockchainImage` as @D4nte suggested below.

**Comment by D4nte** [comment]
I don't agree with the Suggestion because the functionality is already split.

My recommendation would just move the `new` function from `Image` to the `BlockchainImage` trait.

**Comment by bonomat** [comment]
@luckysori : @da-kami does not understand

**Comment by thomaseizinger** [comment]
Superseded by https://github.com/comit-network/create-comit-app/issues/40.
