### ISSUE TITLE
Give feedback to the user when images are being pulled

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#43]
# Problem

The user knows that an image in being pulled but does not know the progress.

Some docker images being bigger than other, it would be great to have some feedback.

# Goal

Give useful feedback to the user of `create-comit-app start-env`.

# Recommendation

This can be done by adding an `.inspect` on the stream pulling the image: https://github.com/comit-network/create-comit-app/blob/28780094c2d882dedb1a911f9b9ba685e5b2cc94/src/docker/mod.rs#L121

That prints some progress.

Or something better/more clever :)

Two ways to go:
A. Have a generic visual aid that moves everytime there is some progress (for example, something like `|/-\|/-|`... so it looks like it rotates when it's pulling
B. Actually decode the data provided by the docker api to show percentage completion.

**Comment by D4nte** [comment]
Parity is big/slow to download so I'd try to add a `.` every few seconds instead of just displaying "Downloading" as done with #59.

**Comment by thomaseizinger** [comment]
I would be keen to use this here: https://docs.rs/indicatif/0.13.0/indicatif/index.html
