### ISSUE TITLE
bitcoincore-rpc client is not async

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#48]
## Problem: 
The bitcoincore-rpc client we are using is not async and hence blocks the current thread during execution. This is not good because the remaining code is based on futures and hence the executor cannot do its work.

## Goal: 
Don't block the executor thread.

## Recommendation:
~We only use the client to generate blocks and fund.~

~Remove the dependency on the client and handcraft the JSON-rpc request with an async HTTP client like reqwest.~

Look into building an image on the fly using shiplift crate that:
- Generate 101 blocks
- Do the funding
- Update contrab to do regular block generation

**Comment by D4nte** [comment]
or `ureq` :)
