### ISSUE TITLE
Create a new release where btsieve is already integrated in cnd

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#52]
Problem: btsieve is hard to explain - now that it is integrated in cnd we should not have to mention it.

Goal: Not have to explain btsieve in Osaka

Proposal: After cnd remove btsieve from startup. Adapt the cnd config creation if needed.

**Comment by D4nte** [comment]
Will release once #54 is done.

**Comment by D4nte** [comment]
Done with #62
