### ISSUE TITLE
No automatic tests

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#53]
**Problem**: nothing is tested automatically. To check if something works we have to try it out manually.

**Goal**: to be able to verify that the code that we write works as intended.

**Ideas**:
- Test `start_env` and `new` in isolation.
- Maybe write one big integration test that checks that `start_env` and `new` work together.
- See if there are any functions that can be unit tested.

**Comment by D4nte** [comment]
Yes, I thought I already opened an issue.

I think the best way is a `test.sh` file that do the following:

```
./create-comit-app new random_name
check random_name/package.json exists
./create-comit-app start-env > start-env.log 2>&1 &
wait till start-env.log contains the ready log line
yarn install
yarn start > hello-swap.log 2>&1 &
wait till hello-swap.log contains 2 "swap complete" lines or 120s.
pkill yarn
pkill start-env
```

This could be split in 2 functions: one for `new` and one for `start-env`
