### ISSUE TITLE
Setup testnet environment

### ISSUE THREAD

**Issue by bonomat** [comit-network/create-comit-app#56]
## Problem
For now, create-comit-app allows setting up regtest nodes for Ethereum and Bitcoin. While this is suitable for a developer environment it is far away from a real-world setup.
Especially for workshops a testnet setup is more suitable as it enables participants to trade against each other. 

## Goal
Enable create-comit-app to setup a testnet environment with:
* cnd config that uses online blocksources
* for Ethereum: use infura.io
* for Bitcoin: use our bitcoind note running on bobtimus.coblox.tech for now. In the future we might want to change this to an online blocksource.

## Remarks

* Ethereum: 
  * We will either need to provide an API key for infura.io or tell the user to get one herself - I opt for the second option
* Bitcoin
  * We currently rely on bitcoin-rpc in create-comit-app and comit-js-sdk (?) - we can provide the authentication details for our testnet node for a first version and rethink how to handle this in the future;
* Funding of Maker & Taker can be an extra manual step, e.g. we can print their addresses and some faucets which we recommend. The user can then get coins themselves; 
* ERC20 funding: I'm not sure how this can look like, but I would propose to deploy a *fake* ERC20 contract with a *mint* function which is open to the public and when passed in an address, it just mints X tokens for that address.

**Comment by luckysori** [comment]
Superseded by #...
