### ISSUE TITLE
Bounce between maker and taker example

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#67]
## Problem

At the moment Hello-Swap contains both maker and taker and the user sees how they interact but cannot control much. It is difficult to understand 

## Goals

* Be able to understand more clearly that there are two sides. 
* Be able to focus on one side. 
* Be able to "just run one side" of a trade. 

## Proposal

Split the example so one has to run it in two terminals. One terminal is the maker and one the taker. 

Additionally it would be cool to, once/if we have testnet support, be able to run the example with another person. (One person running maker and one person running taker side.)

**Comment by bonomat** [comment]
@da-kami : why is this assigned to me? 
I would agree with the description and only remove the last `Note`.
