### ISSUE TITLE
Improve create-comit-app UX

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#68]
## Problem

create-comit-app usage is still a bit cumbersome as there is the `new` and `start-env` command. Knowing that `start-env` needs to be done in a different repo.

## Goal
 
User types the following commands to run an example:

```
yarn create comit-app foo
cd foo/examples/bar
yarn # Install dependencies
yarn run env # Does create-comit-app start-env and hog the terminal
--- open new terminal
    yarn run swap # Run the example, name of the command is example specific
    # OR
    yarn run taker
    ...
    CTRL-C
--- back to "env" terminal
CTRL-C
```
User types the following commands to run their app:
```
yarn create comit-app foo
cd foo
yarn # Install dependencies
yarn run env
--- open new terminal
    touch bar.js
    yarn add some-deps
    <update package.json with a start command>
   yarn start
   ...
--- back to "env" terminal
CTRL-C
```

**Comment by thomaseizinger** [comment]
Note that the "start" of create-react-app actually blocks the current terminal because it launches a web server.

**Comment by D4nte** [comment]
> Note that the "start" of create-react-app actually blocks the current terminal because it launches a web server.

True, so does our `start` and I don't propose to change that :)
The difference is that we have a `start-env` and we just need to decide how we want to handle.

**Comment by thomaseizinger** [comment]
> > Note that the "start" of create-react-app actually blocks the current terminal because it launches a web server.
> 
> True, so does our `start` and I don't propose to change that :)
> The difference is that we have a `start-env` and we just need to decide how we want to handle.

I commented because of this :)

> Provide a start-env npm command that does the Rust start-env and daemonize it.

If we daemonize it, it is no longer blocking :D

**Comment by D4nte** [comment]
> > > Note that the "start" of create-react-app actually blocks the current terminal because it launches a web server.
> > 
> > 
> > True, so does our `start` and I don't propose to change that :)
> > The difference is that we have a `start-env` and we just need to decide how we want to handle.
> 
> I commented because of this :)
> 
> > Provide a start-env npm command that does the Rust start-env and daemonize it.
> 
> If we daemonize it, it is no longer blocking :D

What I am saying is that you are making this comment because you are saying that `create-comit-app start-env` and `create-comit-app start` are matching commands.

I am saying they are not, and hence, it is fine for `create-comit-app start-env` to not be blocking.

My proposal below, I am talking about `npx create-comit-app`. NOT the Rust binary.
Same row means equivalent commands.

| create-comit-app || create-react-app ||
|--|--|--|--|
| command | description | command | description |
| `cool-app` | Creates a project named `cool-app` (typically runs Rust bin with `new cool-app` | `cool-app` | Create project named `cool-app` |
| `start` | (blocking) Does `start` on the project, typically on hello-swap | `start` | (blocking) Starts the web server|
| `start-env` | Runs blockchain nodes | N/A | No existing equivalent |
| `stop-env` | Stops blockchain nodes | N/A | No existing equivalent |

**Comment by thomaseizinger** [comment]
> What I am saying is that you are making this comment because you are saying that create-comit-app start-env and create-comit-app start are matching commands.

Ah now I got ya! I didn't get that you'd create a new command :)
If we wanna do that, we also gotta think about how we actually want to design this in the JavaScript world. Like:
- what is the npm packages name? (CRA uses `react-scripts`)
- does it wrap a Rust binary or do we implement the functionality in JavaScript?

**Comment by D4nte** [comment]
@thomaseizinger could you come with an addendum proposal to this please?

**Comment by thomaseizinger** [comment]
Sure!

If we were to directly copy the way CRA works then we would need to:

- create an NPM package that does the work of "start-env" (uncreative name: `comit-scripts`)
- `create-comit-app new` would initialize an empty project with `comit-scripts` as a `devDependency` and `comit-sdk` as a dependency.
- `npm start` would call through to `comit-scripts start-env` which would start the blockchain nodes + block the terminal

`comit-scripts` can be implemented in various ways: Either directly in JavaScript or anything else that compiles to it (TypeScript, Rust through WebAssembly, etc). This would also enforce that people are in the correct directory and we can put the .env file there again :)

**Comment by D4nte** [comment]
Let's leave the .env where it is for now :)

So... shall we open a ticket to compile create-comit-app to web assembly?

**Comment by thomaseizinger** [comment]
> So... shall we open a ticket to compile create-comit-app to web assembly?

We can try :sweat_smile: 
Not sure if it is gonna work though!

**Comment by D4nte** [comment]
Keep in `New` until grooming!

**Comment by bonomat** [comment]
All done, we have a beautiful UX
