### ISSUE TITLE
Experiment with snafu for error handling

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#81]
## Problem

CCA is a user-facing CLI and should therefore have good error messages. Currently, we simply Debug-print our error enum variants to the user if something fails.

## Goal

1. Provide good and meaningful error messages to the user.
2. Gain experience with other error handling libraries so that we can also improve the situation in `cnd`.

## Recommendation

Take a look at [snafu](https://crates.io/crates/snafu) and use it in CCA.

**Comment by bonomat** [comment]
@thomaseizinger : did you do this already?

**Comment by thomaseizinger** [comment]
> @thomaseizinger : did you do this already?

Yes, I tried it here: https://github.com/comit-network/create-comit-app/pull/88/commits/5f0042cb5626a424bf390e57da4a6ede24736d16

In the end, I opted for using `anyhow` instead because it is a lot cleaner for a small script like this: https://github.com/comit-network/create-comit-app/pull/88/commits/8969553020850807c9203ecd9cb662c0d272d698

It also works better with IDEs because it doesn't rely on code generation.

cc @luckysori @D4nte @tcharding @da-kami I recommend having a look at the 2nd commit linked in here, `anyhow` is pretty cool :)
