### ISSUE TITLE
Remove the libusb build dependency

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#83]
## Problem

With the introduction of the ERC20 environment (https://github.com/comit-network/create-comit-app/pull/79), we are also now locally signing transaction through emerald. Unfortunately, emerald brings in a compile-time dependency on the shared library `libusb-1.0`.

## Goal

Have CCA be as easy to compile as possible: no dependencies on shared libraries.

## Recommendation

Make a PR to emerald-vault-core to feature-gate whatever code depends on libusb.

**Comment by bonomat** [comment]
@thomaseizinger : did you do this already?

**Comment by thomaseizinger** [comment]
Yes, this was resolved through this commit: https://github.com/comit-network/create-comit-app/pull/79/commits/eddc6d279d7425ec1ef3f51162a4d4afe34fde51
