### ISSUE TITLE
Relax tslint rules or use Javascript

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#89]
@D4nte commented on [Fri Sep 27 2019](https://github.com/comit-network/hello-swap/issues/34)

## Problem

During a workshop/live coding, the linter is cumbersome, especially around unused imports and variables/arguments.
However, we want to keep the hello-swap codebase to a high quality level.

## Goal

Only apply linter when we modify the hello-swap codebase, not when it is used as part of a new project

## Recommendation

Steps:
1. Relax the rules in the default/shipped `tslint.json`.
2. Create a new `tslint-strict.json` file that is used during the CI and commit hooks

---

@D4nte commented on [Wed Oct 16 2019](https://github.com/comit-network/hello-swap/issues/34#issuecomment-542517686)

Findings: none because `tsc` uses options in `tsconfig.json` so both `tsconfig` and `tslint` files should be modified.

**Comment by luckysori** [comment]
Closed due to the new examples structure.
