### ISSUE TITLE
Add automated tests for the env file generation

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/create-comit-app#94]
## Problem

Currently, the serialization of the `env` file is not automatically tested. This causes regressions that are only caught once you try to run it against an example or an application.

Partly, this issue is caused by us not making good use of Rust's type system, hence the compiler cannot check certain things for us (like writing all the variables to the env file).

## Goal

1. Ship stable software to users.
2. Catch errors as early as possible.

## Recommendation

Model the env file as a struct that has a dedicated method for serializing. Write tests for serializing this struct and compare it.

By using a struct instead of the methods on `EnvFile` directly, we already get feedback at compile-time instead of cryptic errors during the e2e tests with the examples.

**Comment by bonomat** [comment]
This will be redundant with the end-to-end tests for create-comit-app #53

**Comment by thomaseizinger** [comment]
I disagree @bonomat.

I'll re-open the issue with the additional goal for this that I didn't mention :sweat_smile:
