### ISSUE TITLE
Location of env file during start-env is unknown

### ISSUE THREAD

**Issue by luckysori** [comit-network/create-comit-app#97]
## Problem

Running `create-comit-app start-env` creates an `env` file somewhere in the file system, but the location is not indicated when running this command. If a user wants to locate the file in order to look at values such as comit node HTTP API endpoints for manual debugging they have to look at the source code.

## Goal

Not require users to read the source code if they want to manually debug or inspect the environment.

## Recommendation

Log its location after `start-env` has finished writing to it.

**Comment by D4nte** [comment]
If #84 is done, would that still be needed? *impatiently waits for Problem description*

**Comment by D4nte** [comment]
> Running create-comit-app start-env creates an env file somewhere in the file system, but the location is not indicated when running this command.

Can you describe the problem in more details? How is it a problem? What do we expect the user to do with the env file?

**Comment by luckysori** [comment]
> Can you describe the problem in more details? How is it a problem? What do we expect the user to do with the env file? Same for the goal.

Is it better now?

**Comment by thomaseizinger** [comment]
> Not require users to read the source code if they want to manually debug or inspect the environment.

If that is the goal, the examples could also print the content after reading it :)

**Comment by D4nte** [comment]
At this stage I believe this is a **nice to have**.

I think this should be done once #181 is sorted and we have decided the objectives of examples in term of devex. Hence I'll mark it as blocked for now.

**Comment by yosriady** [comment]
Yes, I think displaying where the file is in the console and putting it in the project directory makes a lot of sense. So instead of `~/.create-comit-app/env`, how about `~/my-comit-app/.env`?

**Comment by D4nte** [comment]
> Yes, I think displaying where the file is in the console and putting it in the project directory makes a lot of sense. So instead of `~/.create-comit-app/env`, how about `~/my-comit-app/.env`?

because you can have only one env running at a time.
If you were to code 2 separate apps for your maker and taker then you'd need to start the env from one folder and then copy the file across to the other folder.
